### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by Krimatoria** [SmileycorpMC/Atlas-Lib#2]
The version is updated, but he still thinks it needs to be updated.
![image](https://github.com/SmileycorpMC/Atlas-Lib/assets/106809386/c9be87f0-73b4-411b-9a65-24c961ecc53a)
![image](https://github.com/SmileycorpMC/Atlas-Lib/assets/106809386/ddb95298-b2b5-4be6-bbc1-b165b53a36de)

**Comment by SmileycorpMC** [comment]
Yeah I forgot to update the mods.toml file when uploading the last version, it will be fixed when the mod next updates.
